In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/Users/cyding/Downloads/round1_ijcai_18_train_20180301.txt',sep=' ',header=0)

In [3]:
pd.set_option('display.max_columns', 500)

In [4]:
df.head()

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade
0,108641074714126964,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,4505772604969228686,1,1003,2005,3003,282924576738839389,1537236544,4006,5799347067982556520:-1;509660095530134768:-1;5...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
1,5754713551599725161,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2692638157208937547,0,1002,2005,3006,4007979028023783431,1537243232,4001,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
2,842679481291040981,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,5247924392014515924,0,1003,2005,3004,4884875192608989870,1537211052,4001,5799347067982556520:5131280576272319091;725801...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
3,937088850059189027,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2681414445369714628,1,1004,2005,3006,840119421106178602,1537222670,4016,509660095530134768:-1;5799347067982556520:-1;7...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
4,7975697065017708072,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2729475788342039013,0,1002,2005,3001,1736769971710354684,1537271320,4001,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0

In [5]:
df.shape

(478138, 27)

In [6]:
# find the largest 4 abs correlations, the first is "is_trade" itself, the next 3 are the answers
correlation = df.corr()
correlation['is_trade_abs'] = correlation['is_trade'].apply(lambda x : abs(x)) 
correlation.nlargest(4, 'is_trade_abs')

,instance_id,item_id,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,is_trade_abs
is_trade,-0.002158,-0.000168,-0.005311,-0.014622,-0.055895,0.037358,0.013972,0.006077,0.000255,0.008843,0.002628,0.002026,0.002239,-0.003459,-0.009274,-0.012313,-0.003238,-0.000747,-0.017355,-0.000735,-0.015578,-0.016239,-0.016734,1.000000,1.000000
item_price_level,-0.000380,0.026952,-0.098667,0.240088,1.000000,-0.029377,0.083133,0.134814,0.001559,0.008266,0.000044,-0.003089,-0.002872,0.000281,0.023965,0.011926,-0.008429,0.045727,0.341513,0.048414,0.100911,0.099274,0.228606,-0.055895,0.055895
item_sales_level,-0.000263,-0.015316,-0.060640,-0.028618,-0.029377,1.000000,0.853855,0.757697,0.002646,-0.002519,0.002442,0.002084,0.000406,0.002318,0.009675,-0.080792,0.012862,0.463273,0.170366,0.459293,-0.008801,-0.012572,0.097055,0.037358,0.037358
shop_review_positive_rate,-0.000198,0.002110,-0.095923,0.007857,0.341513,0.170366,0.206513,0.220753,-0.001299,0.000530,0.002989,0.000768,0.001516,0.000081,0.007088,-0.031808,0.029416,0.168541,1.000000,0.166854,0.329895,0.322094,0.465756,-0.017355,0.017355

### The answers are 'item_price_level', 'item_sales_level' and 'shop_review_positive_rate'. They make sense because they are all related to what most interest customers.

In [7]:
df['date'] = pd.to_datetime(df['context_timestamp'], unit ='s').apply(lambda x : x.date())

In [8]:
df['date'].unique()

array([datetime.date(2018, 9, 18), datetime.date(2018, 9, 17),
       datetime.date(2018, 9, 20), datetime.date(2018, 9, 21),
       datetime.date(2018, 9, 19), datetime.date(2018, 9, 22),
       datetime.date(2018, 9, 23), datetime.date(2018, 9, 24)],
      dtype=object)

In [9]:
import datetime

In [10]:
recent3days = df[(df['date'] >= datetime.date(2018, 9, 22)) & (df['date'] <= datetime.date(2018, 9, 24))].loc[:, ['item_id', 'is_trade']]

In [18]:
## since trade is 1, non-trade is 0, the tradeOverClick = sum(is_trade)/count(is_trade), which is grouped by (item_id)
recent3daysConversion = recent3days.groupby('item_id').sum()
recent3daysConversion['click'] = recent3days.groupby('item_id').count()
recent3daysConversion['tradeOverClick'] = recent3daysConversion['is_trade'] / recent3daysConversion['click']
recent3daysConversion = recent3daysConversion.drop(columns=['is_trade', 'click'])
recent3daysConversion = recent3daysConversion.reset_index()
## leftjoin by key of "item_id"
recent3daysConversion.head()

            item_id  tradeOverClick
0   696490723789804        0.000000
1  1097631460775571        0.043478
2  1637165183538885        0.000000
3  4055398786868336        0.000000
4  4255654217639344        0.000000

In [19]:
result = pd.merge(df, recent3daysConversion, on= 'item_id', how='left')
result.tail(10)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,date,tradeOverClick
478128,3006683903772995202,7876305779987282497,7908382889764677758;5799347067982556520,2636395404473730413;3163265386149801264;734498...,3351806778234144687,4918413420989329604,8,7,12,13,8472991257928913533,1,1003,2004,3009,4786537798612860266,1537767223,4001,2011981573061447208:-1;5799347067982556520:-1;...,3003432921423401154,16,1.000000,5013,0.977327,0.977367,0.979027,0,2018-09-24,0.000000
478129,810107468384208582,642074399208226630,7908382889764677758;2011981573061447208,2636395404473730413;7344985833148694227;885142...,3351806778234144687,4918413420989329604,7,8,14,13,5037055947392073785,0,1005,2002,3006,1519233034336522512,1537770329,4003,2011981573061447208:2636395404473730413;790838...,3003432921423401154,16,1.000000,5013,0.977327,0.977367,0.979027,0,2018-09-24,0.000000
478130,440724230912710850,8714352873114629036,7908382889764677758;8277336076276184272,2636395404473730413;2488701964620097331;124376...,3351806778234144687,4918413420989329604,7,10,12,12,6952856330249913793,1,1004,2003,3008,315553413967677122,1537770536,4001,2011981573061447208:-1;7447522129235776380:-1;...,3003432921423401154,16,1.000000,5013,0.977327,0.977367,0.979027,0,2018-09-24,0.000000
478131,5307935891681475459,5040834653196495196,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;121077...,2603815409272347112,3948283326616421003,8,10,13,14,4668730476166383174,0,1005,2005,3003,237148683202234671,1537786381,4001,5755694407684602296:5131280576272319091;790838...,6642568563427911256,16,0.993662,5014,0.950846,0.950738,0.945286,0,2018-09-24,0.071429
478132,477737900698382237,5040834653196495196,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;121077...,2603815409272347112,3948283326616421003,8,10,13,14,4341781618055685466,0,1005,2005,3007,4393483968878219694,1537759548,4001,"5755694407684602296:3994732721176203348,200835...",6642568563427911256,16,0.993662,5014,0.950846,0.950738,0.945286,1,2018-09-24,0.071429
478133,5940763769799191887,5040834653196495196,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;121077...,2603815409272347112,3948283326616421003,8,10,13,14,7459595729748359155,0,1003,2005,3005,1328893420195687166,1537746519,4009,8257512457089702259:8895425924056041189;227312...,6642568563427911256,16,0.993662,5014,0.950846,0.950738,0.945286,0,2018-09-23,0.071429
478134,3387284546470665526,5040834653196495196,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;121077...,2603815409272347112,3948283326616421003,8,10,13,14,7033818138392866766,1,1004,2002,3002,4909647369391326062,1537801415,4004,5755694407684602296:-1;7908382889764677758:-1;...,6642568563427911256,16,0.993662,5014,0.950846,0.950738,0.945286,0,2018-09-24,0.071429
478135,5693770660150212848,5040834653196495196,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;121077...,2603815409272347112,3948283326616421003,8,10,13,14,7052469495668520594,1,1003,2002,3003,5902545511841349118,1537793100,4001,5755694407684602296:-1;7908382889764677758:-1,6642568563427911256,16,0.993662,5014,0.950846,0.950738,0.945286,0,2018-09-24,0.071429
478136,4623253188146764341,5040834653196495196,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;121077...,2603815409272347112,3948283326616421003,8,10,13,14,988569127238007467,1,1003,2002,3003,4979257525081659552,1537783729,4001,8257512457089702259:-1;1760164811125093110:203...,6642568563427911256,16,0.993662,5014,0.950846,0.950738,0.945286,0,2018-09-24,0.071429
478137,8013124750038806831,3762437480819554366,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;625945...,6447766541123854191,7322157373578955368,7,3,4,11,3339280989551857799,0,1005,2005,3005,3834452003127934166,1537789701,4006,5755694407684602296:-1;509660095530134768:-1;8...,7591475337333430247,10,0.991431,5008,0.894010,0.886656,0.879810,0,2018-09-24,0.000000